from django.contrib import admin
from .models import Todo

# Allows created_on field to display in Django Admin dash. Normally it doesn't because it is an autogenerated field that cannot be manipulated
class TodoAdmin(admin.ModelAdmin):
  readonly_fields = ('created_on',)
# Register your models here.
admin.site.register(Todo, TodoAdmin)